/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-01-13

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "stm32f4_discovery.h"
#include "serial.h"
#include "vt100.h"
#include "stdint.h"
#include "ecran_init.h"
#include "vaisseau_move.h"
#include <stdbool.h>
#include "missile.h"

#define NB_ENNEMIE (15)




int main(void)
{
	serial_init(115200);
	vt100_clear_screen();

	signed char val_bout;
	uint8_t x;
	uint8_t y;
	unsigned char start = 0;
	uint8_t missile_x = 0;
	uint8_t missile_y = 0;
	uint8_t compteur = 0;
	uint8_t enemy_restant = NB_ENNEMIE;
	uint8_t vaisseau_enn[NB_ENNEMIE][3] = {
			{ 10, 5, false }, { 20, 5, false }, { 30, 5, false },
			{ 40, 7, false }, { 50, 7, false }, { 60, 7, false },
			{ 15, 9, false }, { 25, 9, false }, { 35, 9, false },
			{ 45, 11, false }, { 55, 11, false }, { 65, 11, false },
			{ 5, 13, false }, { 40, 13, false }, { 70, 13, false },};
	uint8_t vaisseau_comp = 0;
	uint8_t delay = 30;

	ecran_init();

	while (start == 0) {
		val_bout = serial_get_last_char();
		if (val_bout == 's') {
			start = 1;
			vt100_clear_screen();
		}
	}
	//affichage des ennemies restant
	vt100_move(60, 1);
	serial_puts("enemy remaining: ");
	vt100_move(77, 1);
	serial_putchar('0' + ((NB_ENNEMIE / 10) % 10)); //dizaine
	vt100_move(78, 1);
	serial_putchar('0' + (NB_ENNEMIE % 10)); //unitaire

	//initialisation du vaisseau
	x = VT100_SCREEN_WIDTH / 2;
	y = 23;
	vt100_move(x, y);
	serial_putchar('^');

	//initialisation des vaisseau ennemies:
	for (uint8_t i = 0; i < NB_ENNEMIE; i++) {
		vt100_move(vaisseau_enn[i][0], vaisseau_enn[i][1]);
		vaisseau_enn[i][2] = true;
		serial_puts("<-H->");
	}

	/* Infinite loop */
  while (1)
  {
		compteur += 1;
	/*detection d'un appuis de touche*/
		val_bout = serial_get_last_char();

		if (val_bout == 'd') {
			x = vaisseau_move(x, y, true);
		}

		if (val_bout == 'q') {
			x = vaisseau_move(x, y, false);
		}

		//initialisation d'un missile si aucun n'est tiré
		if (val_bout == 'z') {
			if ((missile_y == 0) && (missile_x == 0)) {
				missile_x = x;
				missile_y = y - 1;
			}
		}
		//lancement du missile, avec timer si un missile est tiré
		if ((missile_y != 0) && (missile_x != 0)) {
			if (compteur == delay) {
				missile_y = missile(missile_x, missile_y);

				/*recherche de vaisseau toucher par le missile*/
				for (uint8_t x = 0; x < NB_ENNEMIE; x++) {
					/*detection d'un vaisseau ennemie sur toute sa longeur*/
					vaisseau_comp = vaisseau_enn[x][0];
					if ((missile_x >=  vaisseau_comp) && (missile_x <= (vaisseau_comp +4))){
						if (vaisseau_enn[x][1] == missile_y) {
							//si le vaisseau existe alors:
							if (vaisseau_enn[x][2] == true){
								vaisseau_enn[x][2] = false;
								vt100_move(vaisseau_enn[x][0], missile_y);
								serial_puts("     ");
								missile_x = 0;
								missile_y = 0;
							}

						}
					}
				}
				//si missile atteint limite screen -> reset missile
				if (missile_y == 2) {
					vt100_move(missile_x, missile_y);
					serial_putchar(' ');
					missile_x = 0;
					missile_y = 0;
				}
				compteur = 0;
			}
		}
		// comptage des ennemie restant
		enemy_restant = NB_ENNEMIE;
		for (uint8_t i = 0; i < NB_ENNEMIE; i++) {
			if (vaisseau_enn[i][2] == false) {
				enemy_restant -= 1;
			}
		}
		//affichage des ennemies restant
		vt100_move(77, 1);
		serial_putchar('0' + ((enemy_restant / 10) % 10)); //dizaine
		vt100_move(78, 1);
		serial_putchar('0' + (enemy_restant % 10)); //unitaire

		//remise a 0 du compteur
		if (compteur == delay) {
			compteur = 0;
		}
		if (enemy_restant == 0){
			ecran_end();
		}
	}
}



/*
 * Callback used by stm32f4_discovery_audio_codec.c.
 * Refer to stm32f4_discovery_audio_codec.h for more info.
 */
void EVAL_AUDIO_TransferComplete_CallBack(uint32_t pBuffer, uint32_t Size){
  /* TODO, implement your code here */
  return;
}

/*
 * Callback used by stm324xg_eval_audio_codec.c.
 * Refer to stm324xg_eval_audio_codec.h for more info.
 */
uint16_t EVAL_AUDIO_GetSampleCallBack(void){
  /* TODO, implement your code here */
  return -1;
}
